# Generated by Django 4.2 on 2023-04-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("apellido_paterno", models.CharField(max_length=255)),
                ("apellido_materno", models.CharField(max_length=255)),
                ("edad", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.IntegerField()),
            ],
        ),
    ]
